site_name: PROJECT-TEMPLATE-FRONT
site_description: Project documentation of project template front

repo_url: https://github.com/loreal-techaccelerator/project-template-front

theme:
    name: mkdocs
    locale: en
    highlightjs: true
    hljs_languages:
        - yaml

nav:
    - Home: README.md
    - Getting Started: quick-start.md
    - Developer Guide:
        - Typescript: typescript.md
        - Linter Rules: linter-rules.md
        - Linter Editor: linter-editor.md
        - Error Handling: error-handling.md
        - Design: design.md
        - Architecture: architecture.md
